version: '3'

services:
  php:
    build:
      context: .
      dockerfile: DockerFile_PHP
    image: sandboxapp
    container_name: php
    restart: unless-stopped
    volumes:
      - ./:/var/www

  web:
    build:
      context: .
      dockerfile: DockerFile_NGINX
    image: nginx
    container_name: web
    restart: unless-stopped
    ports:
      - "8080:80" # http://localhost:8080
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: db_comference_size
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local